### ISSUE TITLE
Actualizar instruções para desenvolvimento local

### ISSUE THREAD

**Issue by joao** [centraldedados/centraldedados.pt#16]
O Readme.md está desactualizado nas instruções para setup para desenvolvimento local.
Refere as instruções no repositório datacentral, mas essas estão desactualizadas.

Passos a integrar
1) make install
2) make build
3) make serve

Adicionalmente para o url de páginas funcionar localmente, tem de ter '/' no final, exemplo: '/sobre/'

**Comment by rlafuente** [comment]
Fixed :-) ([commit](https://github.com/centraldedados/datacentral/commit/fa9304fb377a5fb1ba5f4cfba1e2019a624e0bcf))
