### ISSUE TITLE
URL partido na descrição do repositório

### ISSUE THREAD

**Issue by hugopeixoto** [centraldedados/centraldedados.pt#24]
Quando vou a https://github.com/centraldedados/centraldedados.pt
a descrição tem um URL: http://www.centraldedados.pt

Este URL não funciona (só funciona sem o www). Não sei se a solução é corrigir o URL ou fazer o www. também funcionar, mas fica aqui o aviso :)

**Comment by rlafuente** [comment]
Epá, tinha-me passado este issue -- bom olho! Obrigado ;-)
