### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by joanavl** [centraldedados/centraldedados.pt#8]
Explicação do que se trata.

**Comment by rlafuente** [comment]
O texto da sidebar atual está [aqui](https://github.com/centraldedados/centraldedados.pt/blob/master/content/welcome_text.md), basta editar e fazer um pull request que podemos integrar no site. A [wiki](https://github.com/centraldedados/centraldedados.pt/wiki) contém alguns rascunhos que podem ser aproveitados para explicar bem o âmbito do site.

**Comment by rlafuente** [comment]
Ufa, finalmente pusemos o raio da [página de about](http://centraldedados.pt/sobre) no ar!
